<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class CreateTblDocumentTypesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::connection('mysql_main')->create('tblDocumentTypes', function (Blueprint $table) {
            $table->id('ID');
            $table->char('Code', 10);
            $table->string('Description', 150);
            $table->dateTime('CreatedAt');
            $table->dateTime('UpdatedAt');
        });

        // Insert all document types
        $now = now();
        DB::connection('mysql_main')->table('tblDocumentTypes')->insert([
            ['Code' => 'NSB', 'Description' => 'PHILIPPINE SEAMAN BOOK', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'PP', 'Description' => 'PHILIPPINE PASSPORT', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'YFEV', 'Description' => 'VACCINATION (YELLOW FEVER)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'PSCRB', 'Description' => 'COP_PROF. IN SURVIVAL CRAFT & RESCUE BOAT', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'BSC', 'Description' => 'COP_STCW \'95 - BASIC SAFETY COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'AFF', 'Description' => 'COP_ADVANCED TRAINING IN FIREFIGHTING', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MEFA', 'Description' => 'COP_MEDICAL EMERGENCY - FIRST AID', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MECA', 'Description' => 'COP_MEDICAL CARE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'NCOC', 'Description' => 'CERTIFICATE OF COMPETENCY FOR OFFICERS', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'NCOE', 'Description' => 'ENDORSEMENT OF CERTIFICATE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'NGMDSS', 'Description' => 'PHILIPPINE GOC', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'FLGMDSS', 'Description' => 'PANAMA GMDSS LICENSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'FLGMDSB', 'Description' => 'PANAMA GMDSS SEAMAN\'S BOOK', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'FL', 'Description' => 'PANAMA LICENSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'FLSB', 'Description' => 'PANAMA SEAMAN BOOK', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'FL', 'Description' => 'JAPANESE COC LICENSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'FLSB', 'Description' => 'JAPANESE SEAMAN BOOK', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'FLSSO', 'Description' => 'JAPANESE SSO - CERT. OF COMPLETION(TRAINING)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'GOC', 'Description' => 'JAPANESE GOC', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'ROC', 'Description' => 'JAPANESE ROC', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => '3RE', 'Description' => 'JAPANESE 3RD GRADE RADIO LICENSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'HS', 'Description' => 'JAPANESE HEALTH SUPERVISOR', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'SCC', 'Description' => 'JAPANESE COOK LICENSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MED', 'Description' => 'MEDICAL CERTIFICATE (PEME)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'ECDIS', 'Description' => 'ECDIS GENERIC', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'SATC', 'Description' => 'COP_SDSD', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'ISM', 'Description' => 'ISM/SMS ONLINE ASSESSMENT', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'ISPS', 'Description' => 'ISPS ONLINE ASSESSMENT', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'FLSSO', 'Description' => 'PANAMA SSO LICENSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'FLSSO', 'Description' => 'COP_SHIP SECURTY OFFICER', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'GOCSB', 'Description' => 'JAPANESE GOC BOOKLET', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'ECDIS_JRC', 'Description' => 'ECDIS JRC 7201/9201', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'ECDIS_FURUNO', 'Description' => 'ECDIS FURUNO FMD-3100/3200/3300', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'NSB', 'Description' => 'CHINESE SEAFARER\'S BOOK', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'PP', 'Description' => 'CHINESE PASSPORT', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'NSB', 'Description' => 'BULGARIAN SEAMAN BOOK', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'PP', 'Description' => 'BULGARIAN PASSPORT', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'NSB', 'Description' => 'UKRANIAN SEAMAN BOOK', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'PP', 'Description' => 'UKRANIAN PASSPORT', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'CEMP', 'Description' => 'CONTRACT', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'SIN_FL', 'Description' => 'SINGAPORE COE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'SIN_GOC', 'Description' => 'SINGAPORE GOC', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'FLSSB', 'Description' => 'PANAMA SSO BOOK', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'FLGMDSS', 'Description' => 'HONGKONG GMDSS', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'FLGMDSS', 'Description' => 'CAYMAN GMDSS', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'NGMDSS', 'Description' => 'CHINESE GMDSS', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => '6340', 'Description' => 'PHILIPPINE NC2 FOR (CHIEF COOK & 2ND COOK)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => '6342', 'Description' => 'PHILIPPINE NC1 FOR (MESSMAN)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => '6250', 'Description' => 'PHILIPPINE COP (II-5 / III-5)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => '2470', 'Description' => 'JAPANESE COOK TRAINING CERTIFICATE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'CTCSC', 'Description' => 'CHINESE TRAINING CERTIFICATE FOR SHIPS COOK', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MIS', 'Description' => 'MARSHALL ISLAND SEAMAN BOOK', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MIL', 'Description' => 'MARSHALL ISLAND LICENSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MSB', 'Description' => 'MALAYSIAN (SID)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'ML', 'Description' => 'MALAYSIAN (COR)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'NC3', 'Description' => 'PHILIPPINE NC3 FOR (CHIEF COOK & 2ND COOK)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => '6500', 'Description' => 'MEDICAL CERTIFICATE (POST MEDICAL)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'AIS', 'Description' => 'AUTOMATIC IDENTIFICATION SYSTEMS', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'FTME', 'Description' => 'FAMILIARIZATION TRAINING IN MOORING EQUIPMENT (FTME)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'ERS', 'Description' => 'ENGINE ROOM SIMULATOR COURSE (ERS/ERM)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'SSBT', 'Description' => 'SHIP SIMULATOR & BRIGDE TEAMWORK w/ BRM', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'FFLB', 'Description' => 'FREE FALL LIFEBOAT FAMILIARIZATION', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'SPFHFC', 'Description' => 'SAFE PRACTICES IN HANDLING FUMIGATED CARGO', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'SMSCRS', 'Description' => 'ISM/SMS V 3.0 (3 DAYS COURSE)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'PNMSDSD', 'Description' => 'PANAMA ENDORSEMENT - SDSD', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'AMCV', 'Description' => 'AUSTRALIAN MARITIME CREW VISA', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'USVISA', 'Description' => 'US VISA', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'ECDIS_JRC_901', 'Description' => 'ECDIS JRC JAN-701/901/901M/701B/901B/2000', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'FLSSOC', 'Description' => 'JAPANESE SSO - CERT. OF QUALIFICATION', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'ECDIS_KLHG', 'Description' => 'ECDIS KELVIN HUGNES - KLHG', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'TTOS_CORONA', 'Description' => 'TTOS - CORONA', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'PP', 'Description' => 'JAPANESE PASSPORT', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => '6251', 'Description' => 'PHILIPPINE COP (II-4 / III-4)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'ECDIS_FURUNO_FEA', 'Description' => 'ECDIS FURUNO FEA - 2807/2107', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'ECDIS_FURUNO_CBT', 'Description' => 'ECDIS FURUNO CBT- 3100/3200/3300', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => '201', 'Description' => 'BIODATA', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MID', 'Description' => 'MARSHALL ISLAND GMDSS', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'SHST', 'Description' => 'SHIP HANDLING TRAINING FOR CAPTAIN', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'KLINEEMS', 'Description' => 'TTOS - KLINE EMS (ENVIRONMENTAL MANAGEMENT SYSTEM)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'TTOS_SPC', 'Description' => 'TTOS SPECIAL OR TTOS MARITIME LEGAL MATTERS', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'BASICNAV', 'Description' => 'TTOS - BASIC NAVIGATION', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'TTOS_PCC', 'Description' => 'TTOS - PCC', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'SSO', 'Description' => 'SHIP SECURITY OFFICER', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'PNMSSO', 'Description' => 'PANAMA ENDORSEMENT - SSO', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'TNKC_BASS', 'Description' => 'BASSNET', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'BRM', 'Description' => 'BRM / BTM', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'TTOS_NISHI', 'Description' => 'TTOS NISHI-F LRRS', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'SRUC', 'Description' => 'SENIOR RATING UPGRADING COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'RDSC', 'Description' => 'REAL DANGER SENSING COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'SEC', 'Description' => 'SKILL ENHANCEMENT COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'SC', 'Description' => 'STEERING COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'HGMC', 'Description' => 'HEALTH & GALLEY MANAGEMENT COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'SCC_IC', 'Description' => 'SPECIAL CUISINE COURSE (INTERNATIONAL COOKING)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'TCD', 'Description' => 'TEAMWORK IN CULTURAL DIVERSITY', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'EW', 'Description' => 'EQ IN THE WORKPLACE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'STRESS_MS', 'Description' => 'STRESS MANAGEMENT SEMINAR', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'ME_COURSE', 'Description' => 'ME / ENGINE FAMILARIZATION COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MCA', 'Description' => 'MALAYSIAN CREW CONTRACT AGREEMENT (SEC)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MAL_PEME', 'Description' => 'MALAYSIAN MEDICAL CERTIFICATE (PEME)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'PNMCC', 'Description' => 'PANAMA ENDORSEMENT - SHIPS COOK COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MS', 'Description' => 'MALAYSIAN SEAMANBOOK', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MP', 'Description' => 'MALAYSIAN PASSPORT', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'LCRA', 'Description' => 'LIBERIAN CRA', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'LSB', 'Description' => 'LIBERIAN SEAMAN BOOK', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'LPP', 'Description' => 'LIBERIAN PASSPORT', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'PNMMED', 'Description' => 'PANAMA MEDICAL CERTIFICATE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'SMSREFC', 'Description' => 'ISPS CODE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'SPASDIG', 'Description' => 'SPAS - DIGITRACE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'CRANEOP', 'Description' => 'CRANE OPERATOR', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'NICKELORE', 'Description' => 'NICKLE ORE CARGO FAMILIARIZATION', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'TTOS-CPIT', 'Description' => 'TTOS - COMPETENCY PROMOTIONAL INHOUSE TRAINING', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'TTOS-ENAV', 'Description' => 'TTOS - E-NAVIGATOR', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'AFFDRUGANDALCO', 'Description' => 'AFFIDAVIT OF DRUG AND ALCOHOL POLICY', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'ENMS', 'Description' => 'ENERGY MANAGEMENT SYSTEM ONLINE COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'LNG', 'Description' => 'HANDLING DANGEROUS AND OTHER SUBSTANCES', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MLC', 'Description' => 'MLC 2006', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'PT', 'Description' => 'PAINTING TECHNIQUE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'RS', 'Description' => 'ROPE SLICING', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'SAF', 'Description' => 'SAFIR', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'GDC', 'Description' => 'GAS DETECTOR CALIBRATION', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'PSB', 'Description' => 'PCC SPECIAL BRIEFING', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'CCD', 'Description' => 'CREW CONSENT DOCUMENT', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'SOCCERT', 'Description' => 'SAFETY OFFICER COURSE CERTIFICATE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'VACTYHEP', 'Description' => 'VACCINATION: TYPHOID FEVER AND HEPA A & B', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'STCW', 'Description' => 'CHINESE STCW COE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'CCOC', 'Description' => 'CHINESE COC', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'CBT_CYBERSEC', 'Description' => 'CYBER SECURITY CERTIFICATE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'VAC_CHICPOX', 'Description' => 'VARICELLA (CHICKEN POX) VACCINE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'PERSAFE', 'Description' => 'PERSONAL SAFETY', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'RFPWMER', 'Description' => 'RATING FORMING PART OF A WATCH IN MANNED ENGINE ROOM', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'EWCA', 'Description' => 'ELECTRIC WELDING COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MOS', 'Description' => 'MOSHI', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'TS', 'Description' => 'TRIM AND STABILITY', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'PHS', 'Description' => 'PEOPLE HANDLING SKILLS', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'BWMS', 'Description' => 'BALLAST WATER MANAGEMENT COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MEMSS', 'Description' => 'MAIN ENGINE MANUEVERING SYSTEM SIMULATOR (NABCO)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'BCCC', 'Description' => 'BOILER COMBUSTION CONTROL COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'FNL', 'Description' => 'FUEL AND LUBRICANTS', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MAM', 'Description' => 'MARINE AND AUXILLARY MACHINERIES', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MARELTEC', 'Description' => 'MARINE ELECTRO-TECHNOLOGY', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'IMC', 'Description' => 'INDUSTRIAL MOTOR CONTROL', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'OAWC', 'Description' => 'OXYGEN_ACETYLENE WELDING COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'LMOC', 'Description' => 'LATHE MACHINE OPERATOR COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MDSLE_OTR1', 'Description' => 'MAIN DIESEL ENGINE OVERHAUL TRAINING 1', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MDSLE_OTR2', 'Description' => 'MAIN DIESEL ENGINE OVERHAUL TRAINING 2', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MDSLE_OTR3', 'Description' => 'MAIN DIESEL ENGINE OVERHAUL TRAINING 3', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MR', 'Description' => 'MARINE REFRIGERATION', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MHV', 'Description' => 'MARINE HIGH VOLTAGE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'AWC', 'Description' => 'ADVANCE WELDING COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'SRUCO1', 'Description' => 'SENIOR RATING UPGRDATING COURSE - OILER #1 (SRUC-E)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'BASIC-IGF', 'Description' => 'COP FOR BASIC IGF (GAS FUEL VESSEL)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'IMSBC', 'Description' => 'IMSBC CODE TRAINING', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'NAVWATCHS_L1', 'Description' => 'NAVIGATIONAL WATCH SIMULATOR LEVEL 1', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'WOODCHIP_FAM', 'Description' => 'WOODCHIP CARRIER FAMILIARIZATION COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'TTOS_ELEVATOR', 'Description' => 'TTOS - MARINE ELEVATOR SAFETY TRAINING', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'DGENG', 'Description' => 'DIESEL GENERATOR ENGINE OVERHAULING TRAINING', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'PUROV', 'Description' => 'PURIFIER OVERHAULING MAINTENANCE COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'TDTST', 'Description' => 'TRADE TEST', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'COVID19', 'Description' => 'GUIDANCE ON PREVENTION AND CONTROL OF COVID-19 ONBOARD', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'BRF', 'Description' => 'PRE DEPARTURE BRIEFING FORM', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'NHIC', 'Description' => 'NEW HIRE ASSESSMENT / CHECKLIST', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'PRMTN', 'Description' => 'PROMOTION ASSESSMENT / CHECKLIST', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'IRLPL', 'Description' => 'INCIDENT REPORT & LOSS PREVENTION LESSON', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'bcb', 'Description' => 'BULK CARRIER BRIEFING', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'pccu', 'Description' => 'PCC UNDERTAKING', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'ecdis-kta', 'Description' => 'ECDIS KNOWLEDGE AND TRAINING ASSURANCE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'cms', 'Description' => 'DECK MACHINERY COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'IGFBT', 'Description' => 'COP IGF BASIC', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'eec', 'Description' => 'ELECTRIC AND ELECTRONIC COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'JCOPIGFAD', 'Description' => 'JAPAN COP IGF (ADVANCE)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'JCOPIGFBA', 'Description' => 'JAPAN COP IGF (BASIC)', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'OU', 'Description' => 'OATH OF UNDERTAKING', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'IMO2020', 'Description' => 'BUNKERING PROCEDURES AND MARPOL VI/IMO 2020', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'cdb', 'Description' => 'CAYMAN DISCHARGE BOOKLET', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'cl', 'Description' => 'CAYMAN LICENSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'cgoc', 'Description' => 'CAYMAN GOC', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'csc', 'Description' => 'CAYMAN SHIP\'S COOK', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'VACHEP', 'Description' => 'VACCINATION: HEPA A & B', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'CDPPCC', 'Description' => 'CARGO DAMAGE PREVENTION FOR PCC', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'BCG', 'Description' => 'BULK CARRIER GUIDELINES', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'LT', 'Description' => 'LOCKOUT TAGOUT', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'SMHW', 'Description' => 'SEAFARER\'S MENTAL HEALTH AND WELLBEING', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'JOTC', 'Description' => 'JUNIOR OFFICER TRAINING COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'UTC', 'Description' => 'UPGRADING TRAINING COURSE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'TSBCTSBGC', 'Description' => 'TRIM & STABILITY FOR BULK CARRIER TRANSPORTING SOLID BULK AND GRAIN CARGOES', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'MOSHID', 'Description' => 'MOSHI - DECK OFFICERS', 'CreatedAt' => $now, 'UpdatedAt' => $now],
            ['Code' => 'IGFADV', 'Description' => 'COP IGF ADVANCE', 'CreatedAt' => $now, 'UpdatedAt' => $now],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::connection('mysql_main')->dropIfExists('tblDocumentTypes');
    }
}